<a href="https://colab.research.google.com/github/aflahaflu6637-design/Python-libraries/blob/main/Copy_of_Untitled21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr=np.array([1,2,3])

print(arr)
print(arr[1])

[1 2 3]
2


In [ ]:
import numpy as np

marks=np.array([45,60,75,90,55])
updated_marks=marks+5

avg_mark=np.mean(updated_marks)

print('Ornginal marks:',marks)
print('Updated Marks: ',updated_marks)
print('Average Mark:',avg_mark)

print(marks.dtype)

print('Avrage mark:',marks.mean())

Ornginal marks: [45 60 75 90 55]
Updated Marks:  [50 65 80 95 60]
Average Mark: 70.0
int64
Avrage mark: 65.0


In [ ]:
import numpy as np

sales=np.array([[250,300,180],
                [320, 290, 210]])

print('Sales: ')
print(sales)

print('Sales per product in 2 weeks :',sales.sum(axis=0))

print('Total sales per week: ',sales.sum(axis=1))
print('Average sales per product: ',sales.mean(axis=0))
print('Average sales per week :',sales.mean(axis=1))
print(sales.shape)
print(sales.dtype)
print(sales.shape)

sales_week=sales.sum(axis=1)
print(sales_week)

total_sales=sales_week.sum(axis=0)
print(total_sales)


sales_per_item=sales.sum(axis=0)
print(sales_per_item)

total_sale=sales_per_item.sum()
print(total_sale)


print('average_sale:',sales.mean())

print(sales.max())

print(sales.max(axis=0))

print(sales.max(axis=1))

Sales: 
[[250 300 180]
 [320 290 210]]
Sales per product in 2 weeks : [570 590 390]
Total sales per week:  [730 820]
Average sales per product:  [285. 295. 195.]
Average sales per week : [243.33333333 273.33333333]
(2, 3)
int64
(2, 3)
[730 820]
1550
[570 590 390]
1550
average_sale: 258.3333333333333
320
[320 300 210]
[300 320]


In [ ]:
import numpy as np

sales=np.array([[250,300,180],
                [320, 290, 210]])



print(sales.ndim)
print(sales.shape)
print(sales.itemsize)
print(sales.nbytes)
print(sales.size)
print(sales.strides)

2
(2, 3)
8
48
6
(24, 8)


In [ ]:
import numpy as np

marks = np.array([[85, 78, 92],
                  [76, 88, 65],
                  [90, 82, 95],
                  [68, 75, 80]])



print("Shape (students, subjects):", marks.shape)
print("Total marks entries:", marks.size)

Shape (students, subjects): (4, 3)
Total marks entries: 12


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])


print(arr.shape)
print(arr.itemsize)
print(arr.size)
print(arr.strides)
print(arr.ndim)

(2, 3)
8
6
(24, 8)
2


In [ ]:

#Array Creation Routines

#What are Array Creation Routines?

#These are special helper functions in NumPy that
#quickly create arrays with common patterns
#(like all zeros, all ones, or a diagonal of 1s) without
#typing every number manually.


#np.array()
#np.zeros(), np.ones()
#np.full(), np.empty()
#np.eye(), np.identity()

In [ ]:


#np.array() → from Python list
#np.zeros() → all zeros
#np.ones() → all ones
#np.full() → all same number
#np.empty() → uninitialized (fast but random values)
#np.eye() / np.identity() → identity matrix (1s on diagonal)



import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)


arr2=np.zeros((2,3))        #(2,3)-->(row,col)
print('\n',arr2)


arr3=np.ones((3,3))        #(3,3)-->(row,col)
print('\n',arr3)


arr4=np.full((3,2),5)       #((3,2),5)-->((row,col),value)
print('\n',arr4)



arr5=np.empty(shape=(2,2))
print('\n', arr5)


arr6=np.eye((3))
print('\n',arr6)


arr7=np.identity((4))
print('\n',arr7)

[1 2 3 4 5]

 [[0. 0. 0.]
 [0. 0. 0.]]

 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

 [[5 5]
 [5 5]
 [5 5]]

 [[1. 1.]
 [1. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Array from Numerical Ranges

#np.arange()
#np.linspace()
#np.logspace()


#What are Numerical Range Functions?


#These are special NumPy functions that create arrays of numbers in a sequence,
#just like counting or making evenly spaced points.



#np.arange() → Counting steps: 0, 1, 2, 3, 4... (like normal counting)
#np.linspace() → Dividing a line into equal parts (like marking every 2 cm on a
#10 cm ruler)
#np.logspace() → Making marks that get bigger faster #
 #(like 1, 10, 100, 1000 — useful in science and finance)

In [ ]:
import numpy as np

print("1. np.arange() - Counting with steps:")
arr1 = np.arange(1, 11)           # start=1, stop=11 (11 not included)
print(arr1)

arr2 = np.arange(0, 20, 5)        # step = 5
print("\nWith step 5:", arr2)

print("\n2. np.linspace() - Evenly spaced numbers:")
arr3 = np.linspace(0, 10, 5)      # 5 numbers from 0 to 10
print(arr3)

print("\n3. np.logspace() - Logarithmic scale:")
arr4 = np.logspace(0, 3, 4)       # 10^0 to 10^3 → 4 numbers
print(arr4)

1. np.arange() - Counting with steps:
[ 1  2  3  4  5  6  7  8  9 10]

With step 5: [ 0  5 10 15]

2. np.linspace() - Evenly spaced numbers:
[ 0.   2.5  5.   7.5 10. ]

3. np.logspace() - Logarithmic scale:
[   1.   10.  100. 1000.]


In [ ]:
import numpy as np

arr1=np.arange(0,11,3)
print(arr1)


arr2=np.linspace(0,5,6)
print(arr2)

[0 3 6 9]
[0. 1. 2. 3. 4. 5.]


In [ ]:
import numpy as np

arr1=np.logspace(0,5,6,base=10)
print(arr1)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04 1.e+05]


In [ ]:
import numpy as np
arr1=np.arange(3,33,6)
print(arr1)

[ 3  9 15 21 27]


In [ ]:
#. Advanced Indexing

#  * Boolean indexing

#  * Fancy indexing

#  * Multi-dimensional indexing




#Boolean Indexing → “Give me all students who scored more than 80”
 #(condition-based)

#Fancy Indexing → “Give me the marks of students number 1, 5, 12, and 25”
 #(list of positions)

#Multi-dimensional Indexing → In a mark sheet
 #(rows = students, columns = subjects), get Math and Science marks for only
 #top students

In [ ]:
import numpy as np

arr = np.array([10, 25, 8, 35, 15, 40, 5])

print("Original array:", arr)

# 1. Boolean Indexing
print("\nBoolean Indexing - Numbers greater than 20:")
bool_mask = arr > 20
print("Boolean mask:", bool_mask)
print("Filtered values:", arr[bool_mask])

# 2. Fancy Indexing
print("\nFancy Indexing - Select indices 0, 2, 5:")
print(arr[[0, 2, 5]])

# 3. Multi-dimensional Indexing
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("\nMulti-dimensional - Get first row and third column:")
print("First row:", matrix[0])
print("Element at row 1, col 2:", matrix[1, 2])

Original array: [10 25  8 35 15 40  5]

Boolean Indexing - Numbers greater than 20:
Boolean mask: [False  True False  True False  True False]
Filtered values: [25 35 40]

Fancy Indexing - Select indices 0, 2, 5:
[10  8 40]

Multi-dimensional - Get first row and third column:
First row: [1 2 3]
Element at row 1, col 2: 6


In [ ]:
import numpy as np

arr=np.array([10,20,30,40,50])

#boolean

pass_con=arr>30
passed=arr[pass_con]
print(passed)

print('\n',arr[arr>30])

print(arr[[0,2]])



[40 50]

 [40 50]
[10 30]


In [ ]:
import numpy as np

marks=np.array([

        [85, 90, 78],
        [40, 55, 60],
        [95, 88, 92]


])

print(marks.sum(axis=0))

print(marks[marks>80])

print(marks[[1,2]])

print(marks[2,2])


print(marks[[0,1,2]])


[220 233 230]
[85 90 95 88 92]
[[40 55 60]
 [95 88 92]]
92
[[85 90 78]
 [40 55 60]
 [95 88 92]]


In [ ]:
import numpy as np

marks = np.array([
    [85, 90, 78],
    [40, 55, 60],
    [95, 88, 92]
])

print("Marks:\n", marks)

# Boolean indexing → students scoring > 80
print("Marks > 80:", marks[marks > 80])

# Fancy indexing → select 1st and 3rd student
print("Selected students:\n", marks[[0, 2]])

# Multi-dimensional → specific element
print("Second student, third subject:", marks[1, 2])

Marks:
 [[85 90 78]
 [40 55 60]
 [95 88 92]]
Marks > 80: [85 90 95 88 92]
Selected students:
 [[85 90 78]
 [95 88 92]]
Second student, third subject: 60


In [ ]:
import numpy as np


val=np.array([
  [10, 50, 30],
 [60, 20, 80],
 [90, 40, 70]
  ])

print(val[val>50])
print(val[[0,2]])
print(val[0,0])


print(val[:,0])


print(val[(val>30) & (val[:,0]>20)])

print(val[:,2])







[60 80 90 70]
[[10 50 30]
 [90 40 70]]
10
[10 60 90]
[50 80 40 70]
[30 80 70]


In [ ]:
#TOPIC: Broadcasting in NumPy

# What is Broadcasting?

# Broadcasting means:
#NumPy automatically adjusts smaller arrays to match bigger arrays so operations
 #can happen without loops

 #Shape A	Shape B	Result
#(3,3)	(1,3)	✅ row-wise
#(3,3)	(3,1)	✅ column-wise
#(3,3)	(2,3)	❌ error

In [ ]:
import numpy as np

# Create array
arr = np.array([10, 20, 30])

# Add scalar (broadcasting)
result = arr + 5

print("Original:", arr)
print("After adding 5:", result)

Original: [10 20 30]
After adding 5: [15 25 35]


In [ ]:
import numpy as np

marks=np.array([
               [50,60,70],
               [80,90,100],
               [40,50,60]
])

bonus=np.array([5,10,15])

final=marks+bonus

print(final)

[[ 55  70  85]
 [ 85 100 115]
 [ 45  60  75]]


In [ ]:
import numpy as np

marks=np.array([
               [50,60,70],
               [80,90,100],
               [40,50,60]
])

bonus=np.array([5,10,15])

final=marks%bonus

print(final)

[[ 0  0 10]
 [ 0  0 10]
 [ 0  0  0]]


In [ ]:
import numpy as np

marks=np.array([
               [50,60,70]])

total=marks+5

print(total)

[[55 65 75]]


In [ ]:
import numpy as np

# 6 marks (1D)
marks = np.array([85, 90, 78, 88, 76, 95])

# Convert to 2 students × 3 subjects
marks_2d = marks.reshape(2, 3)

print("Original:", marks)
print("Reshaped:\n", marks_2d)
print(marks.reshape(3,2))

Original: [85 90 78 88 76 95]
Reshaped:
 [[85 90 78]
 [88 76 95]]
[[85 90]
 [78 88]
 [76 95]]


In [ ]:
import numpy as np

# Create a 1D array with 12 numbers
arr = np.arange(12)
print("Original 1D array:", arr)
print("Original shape:", arr.shape)

# Reshape into different shapes
arr2d = arr.reshape(3, 4)        # 3 rows, 4 columns
print("\nReshaped to (3, 4):\n", arr2d)
print("New shape:", arr2d.shape)

arr2d2 = arr.reshape(2, 6)       # 2 rows, 6 columns
print("\nReshaped to (2, 6):\n", arr2d2)

# Using -1 to let NumPy automatically calculate one dimension
arr_auto = arr.reshape(4, -1)    # -1 means "figure out this dimension"
print("\nReshaped to (4, -1):\n", arr_auto)
print("Auto shape:", arr_auto.shape)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Original shape: (12,)

Reshaped to (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New shape: (3, 4)

Reshaped to (2, 6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Reshaped to (4, -1):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Auto shape: (4, 3)


In [ ]:
import numpy as np

sales_flat = np.array([120, 150, 180, 200, 170, 190,
                       210, 230, 250, 180, 160, 220])

print("Flat sales data:", sales_flat)
print("Total elements:", sales_flat.size)

# Reshape into 2 weeks × 3 days per week
sales_weekly = sales_flat.reshape(4, 3)

print("\nSales organized as 2 weeks × 3 days:\n", sales_weekly)
print("New shape:", sales_weekly.shape)

# Reshape into 3 days × 2 weeks (different view)
sales_by_day = sales_flat.reshape(3, -1)   # -1 auto calculates
print("\nSales by day (3 days × 2 weeks):\n", sales_by_day)

Flat sales data: [120 150 180 200 170 190 210 230 250 180 160 220]
Total elements: 12

Sales organized as 2 weeks × 3 days:
 [[120 150 180]
 [200 170 190]
 [210 230 250]
 [180 160 220]]
New shape: (4, 3)

Sales by day (3 days × 2 weeks):
 [[120 150 180 200]
 [170 190 210 230]
 [250 180 160 220]]


In [ ]:
import numpy as np

num=np.array([1,2,3,4,5,6,7,8])

print(arr.reshape(2, -1))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
### 🔍 Iterating Using Loops

The simplest way to iterate over a NumPy array is by using Python loops.

For a 1D array, iteration is straightforward — each element is accessed one by one using a single loop.

For multi-dimensional arrays:
- A single loop iterates over rows
- Nested loops are required to access each individual element

This method is easy to understand and useful for beginners. However, it is not efficient for large datasets because Python loops are slower compared to NumPy’s optimized operations.


### ⚙️ Using np.nditer()

NumPy provides a built-in iterator called `np.nditer()` for efficient array traversal.

It allows iteration over arrays of any dimension without writing multiple nested loops.

Key points:
- Works for multi-dimensional arrays
- More efficient than standard Python loops
- Provides flexibility in how elements are accessed

This makes `np.nditer()` a preferred choice when dealing with large arrays or performance-critical tasks.


### 🔄 Iterating with Different Orders

NumPy arrays can be iterated in different memory orders, which affects how elements are accessed.

There are two main types:

- **C-order (Row-major order):**
  Elements are stored row by row. Iteration happens across rows first. This is the default in NumPy.

- **F-order (Column-major order):**
  Elements are stored column by column. Iteration happens down columns first.

Understanding iteration order is important because:
- It affects performance
- It determines how data is accessed internally
- It becomes important in large-scale computations

NumPy allows control over iteration order, especially when using functions like `np.nditer()`.

In [9]:
import numpy as np

arr=np.array([

              [1,2],
              [3,4]
])

print('Using loop')

for row in arr:
  for element in row:

    print(element)


for x in np.nditer(arr):
  print(x)

Using loop
1
2
3
4
1
2
3
4


In [41]:
import numpy as np

marks=np.array([

              [78,85,92],
              [65,88,71],
              [95,82,79]
])


count=0

for x in np.nditer(marks,order='F'):
  if x>=80:
    count+=1
    print(x)


print(count)








95
85
88
82
92
5


In [25]:
import numpy as np

marks = np.array([[78, 85, 92],
                  [65, 88, 71],
                  [95, 82, 79]])

print("Student Marks:")
print(marks)

print("\n--- Using np.nditer() with index ---")
count_above_80 = 0

for x in np.nditer(marks):
    print(x, end=" ")
    if x > 80:
        count_above_80 += 1

print("\n\nNumber of students who scored above 80:", count_above_80)

print("\n--- Iterating with different order (Column-wise) ---")
print("Column-major order (F order):")
for x in np.nditer(marks, order='F'):
    print(x, end=" ")

Student Marks:
[[78 85 92]
 [65 88 71]
 [95 82 79]]

--- Using np.nditer() with index ---
78 85 92 65 88 71 95 82 79 

Number of students who scored above 80: 5

--- Iterating with different order (Column-wise) ---
Column-major order (F order):
78 65 95 85 88 82 92 71 79 

In [48]:
import numpy as np

arr=np.arange(1,25,2)
new_arr=arr.reshape(3,4)

print(arr)

print(new_arr)

for x in np.nditer(new_arr,order='C'):
  if x>6:
    print(x)


for x in np.nditer(new_arr,order='F'):
  print(x)

[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
7
9
11
13
15
17
19
21
23
1
9
17
3
11
19
5
13
21
7
15
23


In [77]:
import numpy as np


arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],

])


print(arr[::-1])
print(arr[:,::-1])
print(arr[::-1,::-1])

print(arr.reshape(3,3))

print(np.transpose(arr))

print(arr.reshape(3,3))
print(arr[:,1])

print(arr.transpose())

[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [81]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.vstack((a,b)))

print(np.hstack((a,b)))

print(arr[0:2, 1:3])

print(arr.sort())

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[2 3]
 [5 6]]
None


In [11]:
import numpy as np

a = np.array([[1,2],
              [3,4]])

b = np.array([[5,6],
              [7,8]])

# concatenate
c = np.concatenate((a,b), axis=1)

# stack
h = np.hstack((a,b))
v = np.vstack((a,b))

print("Concatenate:\n", c)
print("Horizontal:\n", h)
print("Vertical:\n", v)
print(a.ravel())



Concatenate:
 [[1 2 5 6]
 [3 4 7 8]]
Horizontal:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
[1 2 3 4]


In [19]:
import numpy as np

arr=np.array([1,2,3,4,5,6])

split_arr=np.array_split(arr,5)
print(split_arr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [34]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

r=np.array_split(a, 3, axis=0)
print(r)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int64)]


In [39]:
import numpy as np
r=np.split(a, 4, axis=1)

print(r)


[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]


In [45]:
import numpy as np

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])


transpose=a.transpose()
print(transpose)

print(a.T)

print(a[1])

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[5 6 7 8]


In [48]:
import numpy as np

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])


print(np.transpose(a))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [53]:
import numpy as np

arr = np.array([
    [[1, 2, 3],
     [4, 5, 6]],

    [[7, 8, 9],
     [10, 11, 12]]
])

print(arr.swapaxes(0,2))

[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [ ]:
🔹 TOPIC: Binary Operators in NumPy

👉 Bitwise operations
👉 Logical operations

1. THEORY (clear + simple)
✅ What are Binary Operators?

👉 Operations that work on two values (element-wise in arrays)


🧠 Real-world analogy

Think:

You compare marks of students
Or combine conditions

👉 Example:

Marks > 50
Marks < 90

In [54]:
import numpy as np

a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 4, 3, 2, 1])

print("a =", a)
print("b =", b)

print("\n--- Bitwise Operations ---")
print("a & b (AND):", a & b)
print("a | b (OR): ", a | b)
print("a ^ b (XOR):", a ^ b)
print("~a (NOT):   ", ~a)

print("\n--- Logical Operations ---")
print("Logical AND:", np.logical_and(a > 2, b < 4))
print("Logical OR: ", np.logical_or(a > 2, b < 4))

a = [0 1 2 3 4]
b = [5 4 3 2 1]

--- Bitwise Operations ---
a & b (AND): [0 0 2 2 0]
a | b (OR):  [5 5 3 3 5]
a ^ b (XOR): [5 5 1 1 5]
~a (NOT):    [-1 -2 -3 -4 -5]

--- Logical Operations ---
Logical AND: [False False False  True  True]
Logical OR:  [False False  True  True  True]


In [57]:
import numpy as np

# Columns: [Math, Science, English]
scores = np.array([[85, 78, 65],
                   [92, 88, 95],
                   [45, 70, 80],
                   [78, 65, 72],
                   [95, 90, 85]])

math = scores[:, 0]
science = scores[:, 1]

print("Math scores:", math)
print("Science scores:", science)

# Using Logical Operations (Recommended for conditions)
good_in_both = np.logical_and(math >= 80, science >= 80)
good_in_one = np.logical_or(math >= 90, science >= 90)

print("\nStudents good in both Math & Science:", good_in_both)
print("Students good in at least one (90+):", good_in_one)


# Using Bitwise operators (very common in NumPy)
excellent = (math >= 85) & (science >= 85)          # AND
outstanding = (math >= 90) | (science >= 90)        # OR

print("\nExcellent students (using &):", excellent)
print("Outstanding students (using |):", outstanding)

# Get actual student scores using boolean indexing
print("\nExcellent students' scores:\n", scores[excellent])

Math scores: [85 92 45 78 95]
Science scores: [78 88 70 65 90]

Students good in both Math & Science: [False  True False False  True]
Students good in at least one (90+): [False  True False False  True]
[[92 88 95]
 [95 90 85]]

Excellent students (using &): [False  True False False  True]
Outstanding students (using |): [False  True False False  True]

Excellent students' scores:
 [[92 88 95]
 [95 90 85]]


In [65]:
scores = np.array([[85, 78, 65],
                   [92, 88, 95],
                   [45, 70, 80],
                   [78, 65, 72],
                   [95, 90, 85]])


print(scores[scores>70])


[85 78 92 88 95 80 78 72 95 90 85]


In [67]:
import numpy as np

a = np.array([2, 3, 5])
b = np.array([1, 4, 2])

print("AND:", a & b)
print("OR :", a | b)
print("XOR:", a ^ b)
print("NOT:", ~a)

print("Left Shift:", a << 1)
print("Right Shift:", a >> 1)
print(np.right_shift(a,1))

AND: [0 0 0]
OR : [3 7 7]
XOR: [3 7 7]
NOT: [-3 -4 -6]
Left Shift: [ 4  6 10]
Right Shift: [1 1 2]
[1 1 2]


In [ ]:
TOPIC: NumPy Mathematical Functions

👉 Trigonometric
👉 Exponential & Logarithmic

1. THEORY (clear + simple)
✅ What are Mathematical Functions in NumPy?

👉 Functions that perform math operations on entire arrays at once

🧠 Real-world analogy

Think:

Instead of calculating sin, log, exp for each value manually
👉 NumPy does it for all values at once
✅ Why do we use them?
No loops (fast ⚡)
Cleaner code
Used in:
Graphs (Matplotlib)
Machine Learning
Physics calculations

In [ ]:
🔹 TOPIC: NumPy Mathematical Functions

👉 Trigonometric
👉 Exponential & Logarithmic

1. THEORY (clear + simple)
✅ What are Mathematical Functions in NumPy?

👉 Functions that perform math operations on entire arrays at once

🧠 Real-world analogy

Think:

Instead of calculating sin, log, exp for each value manually
👉 NumPy does it for all values at once

In [68]:
import numpy as np

angles = np.array([0, 30, 60, 90])

# convert to radians
rad = np.deg2rad(angles)

print("Radians:", rad)

print("sin:", np.sin(rad))
print("cos:", np.cos(rad))

Radians: [0.         0.52359878 1.04719755 1.57079633]
sin: [0.        0.5       0.8660254 1.       ]
cos: [1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]


In [69]:
import numpy as np

angles = np.array([0, np.pi/6, np.pi/4, np.pi/3, np.pi/2])

print("Angles (in radians):", angles)

print("\n--- Trigonometric Functions ---")
print("sin:", np.sin(angles))
print("cos:", np.cos(angles))
print("tan:", np.tan(angles))

print("\n--- Exponential and Logarithmic Functions ---")
numbers = np.array([1, 2, 4, 8, 16])

print("Original numbers:", numbers)
print("e^x (exp):", np.exp(numbers))
print("Natural log (ln):", np.log(numbers))
print("Log base 10:", np.log10(numbers))

Angles (in radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]

--- Trigonometric Functions ---
sin: [0.         0.5        0.70710678 0.8660254  1.        ]
cos: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
tan: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]

--- Exponential and Logarithmic Functions ---
Original numbers: [ 1  2  4  8 16]
e^x (exp): [2.71828183e+00 7.38905610e+00 5.45981500e+01 2.98095799e+03
 8.88611052e+06]
Natural log (ln): [0.         0.69314718 1.38629436 2.07944154 2.77258872]
Log base 10: [0.         0.30103    0.60205999 0.90308999 1.20411998]


In [72]:
import numpy as np


angle=np.array([np.pi/6,np.pi/3,np.pi/2])

print(np.sin(np.deg2rad(angle)))

a=np.array([1,2,3,4,5])

print(np.log10(a))

b=np.array([2,4,8])

print(np.log2(b))



[0.0091384  0.01827603 0.02741213]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[1. 2. 3.]
