<a href="https://colab.research.google.com/github/aflahaflu6637-design/Python-libraries/blob/main/Copy_of_Untitled21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr=np.array([1,2,3])

print(arr)
print(arr[1])

[1 2 3]
2


In [ ]:
import numpy as np

marks=np.array([45,60,75,90,55])
updated_marks=marks+5

avg_mark=np.mean(updated_marks)

print('Ornginal marks:',marks)
print('Updated Marks: ',updated_marks)
print('Average Mark:',avg_mark)

print(marks.dtype)

print('Avrage mark:',marks.mean())

Ornginal marks: [45 60 75 90 55]
Updated Marks:  [50 65 80 95 60]
Average Mark: 70.0
int64
Avrage mark: 65.0


In [ ]:
import numpy as np

sales=np.array([[250,300,180],
                [320, 290, 210]])

print('Sales: ')
print(sales)

print('Sales per product in 2 weeks :',sales.sum(axis=0))

print('Total sales per week: ',sales.sum(axis=1))
print('Average sales per product: ',sales.mean(axis=0))
print('Average sales per week :',sales.mean(axis=1))
print(sales.shape)
print(sales.dtype)
print(sales.shape)

sales_week=sales.sum(axis=1)
print(sales_week)

total_sales=sales_week.sum(axis=0)
print(total_sales)


sales_per_item=sales.sum(axis=0)
print(sales_per_item)

total_sale=sales_per_item.sum()
print(total_sale)


print('average_sale:',sales.mean())

print(sales.max())

print(sales.max(axis=0))

print(sales.max(axis=1))

Sales: 
[[250 300 180]
 [320 290 210]]
Sales per product in 2 weeks : [570 590 390]
Total sales per week:  [730 820]
Average sales per product:  [285. 295. 195.]
Average sales per week : [243.33333333 273.33333333]
(2, 3)
int64
(2, 3)
[730 820]
1550
[570 590 390]
1550
average_sale: 258.3333333333333
320
[320 300 210]
[300 320]


In [ ]:
import numpy as np

sales=np.array([[250,300,180],
                [320, 290, 210]])



print(sales.ndim)
print(sales.shape)
print(sales.itemsize)
print(sales.nbytes)
print(sales.size)
print(sales.strides)

2
(2, 3)
8
48
6
(24, 8)


In [ ]:
import numpy as np

marks = np.array([[85, 78, 92],
                  [76, 88, 65],
                  [90, 82, 95],
                  [68, 75, 80]])



print("Shape (students, subjects):", marks.shape)
print("Total marks entries:", marks.size)

Shape (students, subjects): (4, 3)
Total marks entries: 12


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])


print(arr.shape)
print(arr.itemsize)
print(arr.size)
print(arr.strides)
print(arr.ndim)

(2, 3)
8
6
(24, 8)
2
